### ISSUE TITLE
In regards to plugins.

### ISSUE THREAD

**Issue by Akarias** [XboxChaos/Assembly#204]
Taking BlamCore's tag definitions into consideration, should we look into merging the current plugin set with that of BlamCore's?

There is a couple of issues with generated scnr plugins but they can be worked around. Thought I'd ask before I went through the task of merging all known offsets.

**Comment by Lord-Zedd** [comment]
If you have an easy method for it or something, perhaps. I was kept in the loop for a lot of changes to the BlamCore plugins but I know some stuff snuck past. I say easy method because the current option to export as assembly plugins is buggy and no "pretty" names are stored. Anything there would need to be matched by hand.

**Comment by Lord-Zedd** [comment]
I seem to have lost the file but when I was sent exported plugins before it seems like the names were fairly basic in comparison to the real plugin set. But if you do want to try merging, I'd prefer you send the merged plugins to me rather than via a pull request so I can further merge with any unpublished changes I have.

**Comment by Akarias** [comment]
Not a problem, I'll spend a few hours tomorrow fixing up exported BlamCore plugins.

**Comment by Akarias** [comment]
Example post export: 
https://i.imgur.com/sJNB6MR.jpg

**Comment by Akarias** [comment]
I may have missed the odd bitfield or comment but should be mostly complete https://pastebin.com/r773nGQH

**Comment by Lord-Zedd** [comment]
Comparing to the original plugin, you can see the issues I have with the blamcore plugins. But I marked what appears to be new and I'll go over them.
