### ISSUE TITLE
Can't remove tags

### ISSUE THREAD

**Issue by Letfordlay** [XboxChaos/Assembly#209]
I may just be stupid and can't find the option anywhere, but how do you remove an unneeded tag? If I duplicate a tag and make a modification to one and don't need the other anymore, how do I remove it?

**Comment by Lord-Zedd** [comment]
There is no option to remove tags. Doing so has the potential to cause a lot of problems, and anything deleted wouldn't be truly "removed" from the map. I'd suggest making your modded tags separately, then injecting into a fresh map when you are finished.

**Comment by MegaMech** [comment]
Is the reason we cannot remove tags because it would basically just replace that block with zeros? Then the program would not know where the block started/ended? And refilling that area could be annoying because if you import a tag bigger it won't fit and if you import a smaller tag... Like it's just a mess of problems like that?

Is there a possibility of removing imported tags or zeroing imported tags? If you could atleast replace all the data with null values then the map will not use as much data.

Or perhaps another work around: Imported tags could go to a specific section of map files. Providing assembly the flexibility of doing whatever it wanted in the "mod" section. Or maybe assembly could be programmed to work in two or three copies of a map. A test map and a final map. If the test works you submit the tags to final. If it doesn't the test map gets replaced with the previous version? Or perhaps we're better off just doing that manually?
