### ISSUE TITLE
Possible to convert maps from 360 Reach to MCC Reach?

### ISSUE THREAD

**Issue by spiral6** [XboxChaos/Assembly#220]

**Comment by JacobPozaic** [comment]
Already had been looking into it, It appears the formats do very greatly ( file size difference alone is immense, and it seems some of the strings have changed ).  Microsoft will be doing a 1 time only transfer of custom maps and game modes shared from the original console games to PC because they determined the conversions to be 'too intensive' to actively convert them, leading me to believe that there's going to have to be some new legwork to get the ball rolling on MCC homebrew editors.

**Comment by Lord-Zedd** [comment]
wont be happening. 360 forge variants are already compatible in mcc if thats what you meant.

**Comment by spiral6** [comment]
If that's the case, any tutorial or notes on how to transfer it from 360 to MCC?

**Comment by spiral6** [comment]
https://www.halowaypoint.com/en-us/forums/f3681fbc78fa43878c4aec9a63a46224/topics/how-to-convert-360-reach-variants-for-mcc-reach-pc/3e88a46d-ec10-457b-914c-10b4e4ea23dd/posts?page=1
