### ISSUE TITLE
Suggestion - View hsc string table.

### ISSUE THREAD

**Issue by matty45** [XboxChaos/Assembly#250]
Hello, ive noticed while editing blamscript that there is no easy way to see the list of all the strings a script uses. 
It would be nice if there is a way to get one since all i do is put a random number in the string table offset of the script expressions and hope its the right one, lol.

**Comment by Akarias** [comment]
Heya. 

To get the right decimal offset for your string table just copy the script string table into a file of your hex editor. You can get all the offsets you need there, make changes, add new strings etc. When you are done just overwrite the existing table with your modified one. (Ctrl+B for editors like HxD)

Strings are not required for most expressions outside of allowing the decompiler to correctly display any custom expressions that you write. Eg quoted expressions such as AI expressions, otherwise just an empty quote pair will be shown.

Really the decompiler should check the expression and read the data from the relevant scenario blocks rather than the StringTable, resolve the stringID and display it in the quotes.

I have some changes that exist on my local branch for making script editing easier, like pairing datum attribute to the text displayed in the ScriptEditor decompiler output.

**Comment by Lord-Zedd** [comment]
Closing since Assembly has since added the ability to compile scripts.
