### ISSUE TITLE
No Executable Project Solution

### ISSUE THREAD

**Issue by crowsWithHats** [XboxChaos/Assembly#294]
I'm trying to run Assembly developer branch due to it being updated to the new Forge patch, and I'm using this semi-old tutorial to help me. https://www.youtube.com/watch?v=ygzJvCNeLp8 . I'm a bit of a coding noob and so I can't figure out how to solve this probably simple issue where it's missing an executable.
![image](https://user-images.githubusercontent.com/68412422/87748262-07174a00-c7bb-11ea-8d19-263bb3e1e630.png)
If someone could just point me somewhere or give me the steps to fix it and be on my way that'd be nice.

**Comment by Lord-Zedd** [comment]
Things have changed some since that video was posted so its not as accurate for compiling. Just that image its hard to say what the issue is.
However, the downloader under releases will give a build that supports the new update, though its currently lagging behind the current code on some bugs, which is where appveyor comes in and will have the latest available pre-compiled builds as they happen https://ci.appveyor.com/project/ThunderWaffle/assembly/build/artifacts

**Comment by crowsWithHats** [comment]
ah, thanks man! thought it might be a case of being outdated, glad that you took time to help!
