### ISSUE TITLE
Remastered sound option in sound tags?

### ISSUE THREAD

**Issue by ThatSameer** [XboxChaos/Assembly#360]
**Describe the bug**
Is 'Remastered Sound' under snd! tags no longer an option or is missing? It seemed to be an option in earlier Assembly (looking at tutorial videos) and is an option in other tag editing kits.

**To Reproduce**
1. Go to a sound tag under snd!
2. There should be a 'Remastered Sound' option referencing the remastered sound tag?

**Screenshots**
Current Assembly:

![image](https://github.com/XboxChaos/Assembly/assets/84995410/25fc04ae-ba59-4d98-abb9-f19a01385a1b)

Older Assembly from tutorial:

![image](https://github.com/XboxChaos/Assembly/assets/84995410/1b0736f9-b06d-47a2-8244-9a7a3eb5f418)

**PC (please complete the following information):**
 - OS: Windows 10
 - Assembly version: 2023.07.14.11.33.10-master

**Additional context**
Halo 2 MCC, any scenario, any sound tag

**Comment by Lord-Zedd** [comment]
Checking the history, this change happened for the Season 8 update, the reference was moved into a block in the ugh/sound_cache_file_gestalt tag. The index to it can be seen in your first image as "[ugh!] Remastered Sound Reference Index".
The reference is still seen in the original place in Guerilla because there are actually two different sound tag groups, and when a map is made it gets converted to the one seen in Assembly containing indices to the gestalt tag.
If you follow the index I mentioned to the "Remastered Sound" block in ugh you'll see the tag reference you want.

**Comment by ThatSameer** [comment]
Sorry for not responding earlier. Thank you very much for clarifying 👍
