### ISSUE TITLE
question: extract all tags from Halo CE

### ISSUE THREAD

**Issue by vegerot** [XboxChaos/Assembly#362]
I am trying to edit a Scenario file in Sapien.  To do that I need to extract the scenario tag from the Halo CE `crashsite.map`.  Is there a way to do that in Assembly?

I can see the "extract" options for maps from other Halo games, and I do see the "Dump Full Tag List" option in Halo CE, but I don't see how I can extract the tags the way I want to.

I haven't modded Halo in 15 years so I'd appreciate any help :)

**Comment by Lord-Zedd** [comment]
Assembly's extract uses a custom format that is nowhere close to official tag files. Other games have it because its more trivial to import these files back into another map, H1 and H2 not so much. What you want is Invader https://github.com/SnowyMouse/invader which should be able to dump to actual tag files.

**Comment by vegerot** [comment]
Perfect!  Thank you
